package com.quickscan.core.ui.component

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathBuilder
import androidx.compose.ui.unit.dp

/*
 * Lucide v1.54.0 (ISC License, https://lucide.dev). Path data is taken verbatim
 * from the published 24x24 SVGs and emitted as stroke-only ImageVectors, so
 * Icon() tints them the way the mockups tint their inlined SVGs. Stroke width 2,
 * round caps and joins are Lucide's defaults.
 *
 * Generated by tools/lucide_to_kt.py - do not edit by hand.
 */

private fun lucide(name: String, block: PathBuilder.() -> Unit): ImageVector =
    ImageVector.Builder(
        name = name,
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 24f,
        viewportHeight = 24f,
    ).addPath(
        pathData = PathBuilder().apply(block).nodes,
        fill = null,
        stroke = SolidColor(Color.Black),
        strokeLineWidth = 2f,
        strokeLineCap = StrokeCap.Round,
        strokeLineJoin = StrokeJoin.Round,
    ).build()


val LucideArrowRight = lucide("ArrowRight") {
    moveTo(5f, 12f)
    horizontalLineTo(19f)
    moveTo(12f, 5f)
    lineTo(19f, 12f)
    lineTo(12f, 19f)
}


val LucideBell = lucide("Bell") {
    moveTo(10.268f, 21f)
    arcTo(2f, 2f, 0f, false, false, 13.732f, 21f)
    moveTo(3.262f, 15.326f)
    arcTo(1f, 1f, 0f, false, false, 4f, 17f)
    horizontalLineTo(20f)
    arcTo(1f, 1f, 0f, false, false, 20.74f, 15.327f)
    curveTo(19.41f, 13.956f, 18f, 12.499f, 18f, 8f)
    arcTo(6f, 6f, 0f, false, false, 6f, 8f)
    curveTo(6f, 12.499f, 4.589f, 13.956f, 3.262f, 15.326f)
}


val LucideBookmark = lucide("Bookmark") {
    moveTo(17f, 3f)
    arcTo(2f, 2f, 0f, false, true, 19f, 5f)
    verticalLineTo(20f)
    arcTo(1f, 1f, 0f, false, true, 17.504f, 20.868f)
    lineTo(12.992f, 18.29f)
    arcTo(2f, 2f, 0f, false, false, 11.008f, 18.29f)
    lineTo(6.496f, 20.868f)
    arcTo(1f, 1f, 0f, false, true, 5f, 20f)
    verticalLineTo(5f)
    arcTo(2f, 2f, 0f, false, true, 7f, 3f)
    close()
}


val LucideCamera = lucide("Camera") {
    moveTo(13.997f, 4f)
    arcTo(2f, 2f, 0f, false, true, 15.757f, 5.05f)
    lineTo(16.243f, 5.95f)
    arcTo(2f, 2f, 0f, false, false, 18.003f, 7f)
    horizontalLineTo(20f)
    arcTo(2f, 2f, 0f, false, true, 22f, 9f)
    verticalLineTo(18f)
    arcTo(2f, 2f, 0f, false, true, 20f, 20f)
    horizontalLineTo(4f)
    arcTo(2f, 2f, 0f, false, true, 2f, 18f)
    verticalLineTo(9f)
    arcTo(2f, 2f, 0f, false, true, 4f, 7f)
    horizontalLineTo(5.997f)
    arcTo(2f, 2f, 0f, false, false, 7.756f, 5.952f)
    lineTo(8.245f, 5.048f)
    arcTo(2f, 2f, 0f, false, true, 10.004f, 4f)
    close()
    moveTo(9f, 13f)
    arcTo(3f, 3f, 0f, true, false, 15f, 13f)
    arcTo(3f, 3f, 0f, true, false, 9f, 13f)
}


val LucideCheck = lucide("Check") {
    moveTo(20f, 6f)
    lineTo(9f, 17f)
    lineTo(4f, 12f)
}


val LucideChevronDown = lucide("ChevronDown") {
    moveTo(6f, 9f)
    lineTo(12f, 15f)
    lineTo(18f, 9f)
}


val LucideChevronLeft = lucide("ChevronLeft") {
    moveTo(15f, 18f)
    lineTo(9f, 12f)
    lineTo(15f, 6f)
}


val LucideChevronRight = lucide("ChevronRight") {
    moveTo(9f, 18f)
    lineTo(15f, 12f)
    lineTo(9f, 6f)
}


val LucideCircleX = lucide("CircleX") {
    moveTo(2f, 12f)
    arcTo(10f, 10f, 0f, true, false, 22f, 12f)
    arcTo(10f, 10f, 0f, true, false, 2f, 12f)
    moveTo(15f, 9f)
    lineTo(9f, 15f)
    moveTo(9f, 9f)
    lineTo(15f, 15f)
}


val LucideClipboardCheck = lucide("ClipboardCheck") {
    moveTo(9f, 2f)
    lineTo(15f, 2f)
    arcTo(1f, 1f, 0f, false, true, 16f, 3f)
    lineTo(16f, 5f)
    arcTo(1f, 1f, 0f, false, true, 15f, 6f)
    lineTo(9f, 6f)
    arcTo(1f, 1f, 0f, false, true, 8f, 5f)
    lineTo(8f, 3f)
    arcTo(1f, 1f, 0f, false, true, 9f, 2f)
    close()
    moveTo(16f, 4f)
    horizontalLineTo(18f)
    arcTo(2f, 2f, 0f, false, true, 20f, 6f)
    verticalLineTo(20f)
    arcTo(2f, 2f, 0f, false, true, 18f, 22f)
    horizontalLineTo(6f)
    arcTo(2f, 2f, 0f, false, true, 4f, 20f)
    verticalLineTo(6f)
    arcTo(2f, 2f, 0f, false, true, 6f, 4f)
    horizontalLineTo(8f)
    moveTo(9f, 14f)
    lineTo(11f, 16f)
    lineTo(15f, 12f)
}


val LucideClipboardPaste = lucide("ClipboardPaste") {
    moveTo(11f, 14f)
    horizontalLineTo(21f)
    moveTo(16f, 4f)
    horizontalLineTo(18f)
    arcTo(2f, 2f, 0f, false, true, 20f, 6f)
    verticalLineTo(7.344f)
    moveTo(17f, 18f)
    lineTo(21f, 14f)
    lineTo(17f, 10f)
    moveTo(8f, 4f)
    horizontalLineTo(6f)
    arcTo(2f, 2f, 0f, false, false, 4f, 6f)
    verticalLineTo(20f)
    arcTo(2f, 2f, 0f, false, false, 6f, 22f)
    horizontalLineTo(18f)
    arcTo(2f, 2f, 0f, false, false, 19.793f, 20.887f)
    moveTo(9f, 2f)
    lineTo(15f, 2f)
    arcTo(1f, 1f, 0f, false, true, 16f, 3f)
    lineTo(16f, 5f)
    arcTo(1f, 1f, 0f, false, true, 15f, 6f)
    lineTo(9f, 6f)
    arcTo(1f, 1f, 0f, false, true, 8f, 5f)
    lineTo(8f, 3f)
    arcTo(1f, 1f, 0f, false, true, 9f, 2f)
    close()
}


val LucideCopy = lucide("Copy") {
    moveTo(10f, 8f)
    lineTo(20f, 8f)
    arcTo(2f, 2f, 0f, false, true, 22f, 10f)
    lineTo(22f, 20f)
    arcTo(2f, 2f, 0f, false, true, 20f, 22f)
    lineTo(10f, 22f)
    arcTo(2f, 2f, 0f, false, true, 8f, 20f)
    lineTo(8f, 10f)
    arcTo(2f, 2f, 0f, false, true, 10f, 8f)
    close()
    moveTo(4f, 16f)
    curveTo(2.9f, 16f, 2f, 15.1f, 2f, 14f)
    verticalLineTo(4f)
    curveTo(2f, 2.9f, 2.9f, 2f, 4f, 2f)
    horizontalLineTo(14f)
    curveTo(15.1f, 2f, 16f, 2.9f, 16f, 4f)
}


val LucideDownload = lucide("Download") {
    moveTo(12f, 15f)
    verticalLineTo(3f)
    moveTo(21f, 15f)
    verticalLineTo(19f)
    arcTo(2f, 2f, 0f, false, true, 19f, 21f)
    horizontalLineTo(5f)
    arcTo(2f, 2f, 0f, false, true, 3f, 19f)
    verticalLineTo(15f)
    moveTo(7f, 10f)
    lineTo(12f, 15f)
    lineTo(17f, 10f)
}


val LucideEllipsis = lucide("Ellipsis") {
    moveTo(11f, 12f)
    arcTo(1f, 1f, 0f, true, false, 13f, 12f)
    arcTo(1f, 1f, 0f, true, false, 11f, 12f)
    moveTo(18f, 12f)
    arcTo(1f, 1f, 0f, true, false, 20f, 12f)
    arcTo(1f, 1f, 0f, true, false, 18f, 12f)
    moveTo(4f, 12f)
    arcTo(1f, 1f, 0f, true, false, 6f, 12f)
    arcTo(1f, 1f, 0f, true, false, 4f, 12f)
}


val LucideExternalLink = lucide("ExternalLink") {
    moveTo(15f, 3f)
    horizontalLineTo(21f)
    verticalLineTo(9f)
    moveTo(10f, 14f)
    lineTo(21f, 3f)
    moveTo(18f, 13f)
    verticalLineTo(19f)
    arcTo(2f, 2f, 0f, false, true, 16f, 21f)
    horizontalLineTo(5f)
    arcTo(2f, 2f, 0f, false, true, 3f, 19f)
    verticalLineTo(8f)
    arcTo(2f, 2f, 0f, false, true, 5f, 6f)
    horizontalLineTo(11f)
}


val LucideEye = lucide("Eye") {
    moveTo(2.062f, 12.348f)
    arcTo(1f, 1f, 0f, false, true, 2.062f, 11.652f)
    arcTo(10.75f, 10.75f, 0f, false, true, 21.938f, 11.652f)
    arcTo(1f, 1f, 0f, false, true, 21.938f, 12.348f)
    arcTo(10.75f, 10.75f, 0f, false, true, 2.062f, 12.348f)
    moveTo(9f, 12f)
    arcTo(3f, 3f, 0f, true, false, 15f, 12f)
    arcTo(3f, 3f, 0f, true, false, 9f, 12f)
}


val LucideEyeOff = lucide("EyeOff") {
    moveTo(10.733f, 5.076f)
    arcTo(10.744f, 10.744f, 0f, false, true, 21.938f, 11.651f)
    arcTo(1f, 1f, 0f, false, true, 21.938f, 12.347f)
    arcTo(10.747f, 10.747f, 0f, false, true, 20.494f, 14.837f)
    moveTo(14.084f, 14.158f)
    arcTo(3f, 3f, 0f, false, true, 9.842f, 9.916f)
    moveTo(17.479f, 17.499f)
    arcTo(10.75f, 10.75f, 0f, false, true, 2.062f, 12.348f)
    arcTo(1f, 1f, 0f, false, true, 2.062f, 11.652f)
    arcTo(10.75f, 10.75f, 0f, false, true, 6.508f, 6.509f)
    moveTo(2f, 2f)
    lineTo(22f, 22f)
}


val LucideGlobe = lucide("Globe") {
    moveTo(2f, 12f)
    arcTo(10f, 10f, 0f, true, false, 22f, 12f)
    arcTo(10f, 10f, 0f, true, false, 2f, 12f)
    moveTo(12f, 2f)
    arcTo(14.5f, 14.5f, 0f, false, false, 12f, 22f)
    arcTo(14.5f, 14.5f, 0f, false, false, 12f, 2f)
    moveTo(2f, 12f)
    horizontalLineTo(22f)
}


val LucideHardDrive = lucide("HardDrive") {
    moveTo(10f, 16f)
    horizontalLineTo(10.01f)
    moveTo(2.212f, 11.577f)
    arcTo(2f, 2f, 0f, false, false, 2f, 12.473f)
    verticalLineTo(18f)
    arcTo(2f, 2f, 0f, false, false, 4f, 20f)
    horizontalLineTo(20f)
    arcTo(2f, 2f, 0f, false, false, 22f, 18f)
    verticalLineTo(12.473f)
    arcTo(2f, 2f, 0f, false, false, 21.788f, 11.577f)
    lineTo(18.55f, 5.11f)
    arcTo(2f, 2f, 0f, false, false, 16.76f, 4f)
    horizontalLineTo(7.24f)
    arcTo(2f, 2f, 0f, false, false, 5.45f, 5.11f)
    close()
    moveTo(21.946f, 12.013f)
    horizontalLineTo(2.054f)
    moveTo(6f, 16f)
    horizontalLineTo(6.01f)
}


val LucideHistory = lucide("History") {
    moveTo(3f, 12f)
    arcTo(9f, 9f, 0f, true, false, 12f, 3f)
    arcTo(9.75f, 9.75f, 0f, false, false, 5.26f, 5.74f)
    lineTo(3f, 8f)
    moveTo(3f, 3f)
    verticalLineTo(8f)
    horizontalLineTo(8f)
    moveTo(12f, 7f)
    verticalLineTo(12f)
    lineTo(16f, 14f)
}


val LucideImage = lucide("Image") {
    moveTo(5f, 3f)
    lineTo(19f, 3f)
    arcTo(2f, 2f, 0f, false, true, 21f, 5f)
    lineTo(21f, 19f)
    arcTo(2f, 2f, 0f, false, true, 19f, 21f)
    lineTo(5f, 21f)
    arcTo(2f, 2f, 0f, false, true, 3f, 19f)
    lineTo(3f, 5f)
    arcTo(2f, 2f, 0f, false, true, 5f, 3f)
    close()
    moveTo(7f, 9f)
    arcTo(2f, 2f, 0f, true, false, 11f, 9f)
    arcTo(2f, 2f, 0f, true, false, 7f, 9f)
    moveTo(21f, 15f)
    lineTo(17.914f, 11.914f)
    arcTo(2f, 2f, 0f, false, false, 15.086f, 11.914f)
    lineTo(6f, 21f)
}


val LucideInfo = lucide("Info") {
    moveTo(2f, 12f)
    arcTo(10f, 10f, 0f, true, false, 22f, 12f)
    arcTo(10f, 10f, 0f, true, false, 2f, 12f)
    moveTo(12f, 16f)
    verticalLineTo(12f)
    moveTo(12f, 8f)
    horizontalLineTo(12.01f)
}


val LucideLink = lucide("Link") {
    moveTo(10f, 13f)
    arcTo(5f, 5f, 0f, false, false, 17.54f, 13.54f)
    lineTo(20.54f, 10.54f)
    arcTo(5f, 5f, 0f, false, false, 13.47f, 3.47f)
    lineTo(11.75f, 5.18f)
    moveTo(14f, 11f)
    arcTo(5f, 5f, 0f, false, false, 6.46f, 10.46f)
    lineTo(3.46f, 13.46f)
    arcTo(5f, 5f, 0f, false, false, 10.53f, 20.53f)
    lineTo(12.24f, 18.82f)
}


val LucideLock = lucide("Lock") {
    moveTo(5f, 11f)
    lineTo(19f, 11f)
    arcTo(2f, 2f, 0f, false, true, 21f, 13f)
    lineTo(21f, 20f)
    arcTo(2f, 2f, 0f, false, true, 19f, 22f)
    lineTo(5f, 22f)
    arcTo(2f, 2f, 0f, false, true, 3f, 20f)
    lineTo(3f, 13f)
    arcTo(2f, 2f, 0f, false, true, 5f, 11f)
    close()
    moveTo(7f, 11f)
    verticalLineTo(7f)
    arcTo(5f, 5f, 0f, false, true, 17f, 7f)
    verticalLineTo(11f)
}


val LucideMail = lucide("Mail") {
    moveTo(22f, 7f)
    lineTo(13.009f, 12.727f)
    arcTo(2f, 2f, 0f, false, true, 11f, 12.727f)
    lineTo(2f, 7f)
    moveTo(4f, 4f)
    lineTo(20f, 4f)
    arcTo(2f, 2f, 0f, false, true, 22f, 6f)
    lineTo(22f, 18f)
    arcTo(2f, 2f, 0f, false, true, 20f, 20f)
    lineTo(4f, 20f)
    arcTo(2f, 2f, 0f, false, true, 2f, 18f)
    lineTo(2f, 6f)
    arcTo(2f, 2f, 0f, false, true, 4f, 4f)
    close()
}


val LucideMoon = lucide("Moon") {
    moveTo(20.985f, 12.486f)
    arcTo(9f, 9f, 0f, true, true, 11.512f, 3.014f)
    curveTo(11.917f, 2.992f, 12.129f, 3.474f, 11.914f, 3.817f)
    arcTo(6f, 6f, 0f, false, false, 20.182f, 12.085f)
    curveTo(20.526f, 11.87f, 21.007f, 12.081f, 20.985f, 12.486f)
}


val LucidePalette = lucide("Palette") {
    moveTo(12f, 22f)
    arcTo(1f, 1f, 0f, false, true, 12f, 2f)
    arcTo(10f, 9f, 0f, false, true, 22f, 11f)
    arcTo(5f, 5f, 0f, false, true, 17f, 16f)
    horizontalLineTo(14.75f)
    arcTo(1.75f, 1.75f, 0f, false, false, 13.35f, 18.8f)
    lineTo(13.65f, 19.2f)
    arcTo(1.75f, 1.75f, 0f, false, true, 12.25f, 22f)
    close()
    moveTo(13f, 6.5f)
    arcTo(0.5f, 0.5f, 0f, true, false, 14f, 6.5f)
    arcTo(0.5f, 0.5f, 0f, true, false, 13f, 6.5f)
    moveTo(17f, 10.5f)
    arcTo(0.5f, 0.5f, 0f, true, false, 18f, 10.5f)
    arcTo(0.5f, 0.5f, 0f, true, false, 17f, 10.5f)
    moveTo(6f, 12.5f)
    arcTo(0.5f, 0.5f, 0f, true, false, 7f, 12.5f)
    arcTo(0.5f, 0.5f, 0f, true, false, 6f, 12.5f)
    moveTo(8f, 7.5f)
    arcTo(0.5f, 0.5f, 0f, true, false, 9f, 7.5f)
    arcTo(0.5f, 0.5f, 0f, true, false, 8f, 7.5f)
}


val LucidePlus = lucide("Plus") {
    moveTo(5f, 12f)
    horizontalLineTo(19f)
    moveTo(12f, 5f)
    verticalLineTo(19f)
}


val LucideQrCode = lucide("QrCode") {
    moveTo(4f, 3f)
    lineTo(7f, 3f)
    arcTo(1f, 1f, 0f, false, true, 8f, 4f)
    lineTo(8f, 7f)
    arcTo(1f, 1f, 0f, false, true, 7f, 8f)
    lineTo(4f, 8f)
    arcTo(1f, 1f, 0f, false, true, 3f, 7f)
    lineTo(3f, 4f)
    arcTo(1f, 1f, 0f, false, true, 4f, 3f)
    close()
    moveTo(17f, 3f)
    lineTo(20f, 3f)
    arcTo(1f, 1f, 0f, false, true, 21f, 4f)
    lineTo(21f, 7f)
    arcTo(1f, 1f, 0f, false, true, 20f, 8f)
    lineTo(17f, 8f)
    arcTo(1f, 1f, 0f, false, true, 16f, 7f)
    lineTo(16f, 4f)
    arcTo(1f, 1f, 0f, false, true, 17f, 3f)
    close()
    moveTo(4f, 16f)
    lineTo(7f, 16f)
    arcTo(1f, 1f, 0f, false, true, 8f, 17f)
    lineTo(8f, 20f)
    arcTo(1f, 1f, 0f, false, true, 7f, 21f)
    lineTo(4f, 21f)
    arcTo(1f, 1f, 0f, false, true, 3f, 20f)
    lineTo(3f, 17f)
    arcTo(1f, 1f, 0f, false, true, 4f, 16f)
    close()
    moveTo(21f, 16f)
    horizontalLineTo(18f)
    arcTo(2f, 2f, 0f, false, false, 16f, 18f)
    verticalLineTo(21f)
    moveTo(21f, 21f)
    verticalLineTo(21.01f)
    moveTo(12f, 7f)
    verticalLineTo(10f)
    arcTo(2f, 2f, 0f, false, true, 10f, 12f)
    horizontalLineTo(7f)
    moveTo(3f, 12f)
    horizontalLineTo(3.01f)
    moveTo(12f, 3f)
    horizontalLineTo(12.01f)
    moveTo(12f, 16f)
    verticalLineTo(16.01f)
    moveTo(16f, 12f)
    horizontalLineTo(17f)
    moveTo(21f, 12f)
    verticalLineTo(12.01f)
    moveTo(12f, 21f)
    verticalLineTo(20f)
}


val LucideRepeat = lucide("Repeat") {
    moveTo(17f, 2f)
    lineTo(21f, 6f)
    lineTo(17f, 10f)
    moveTo(3f, 11f)
    verticalLineTo(10f)
    arcTo(4f, 4f, 0f, false, true, 7f, 6f)
    horizontalLineTo(21f)
    moveTo(7f, 22f)
    lineTo(3f, 18f)
    lineTo(7f, 14f)
    moveTo(21f, 13f)
    verticalLineTo(14f)
    arcTo(4f, 4f, 0f, false, true, 17f, 18f)
    horizontalLineTo(3f)
}


val LucideScanLine = lucide("ScanLine") {
    moveTo(3f, 7f)
    verticalLineTo(5f)
    arcTo(2f, 2f, 0f, false, true, 5f, 3f)
    horizontalLineTo(7f)
    moveTo(17f, 3f)
    horizontalLineTo(19f)
    arcTo(2f, 2f, 0f, false, true, 21f, 5f)
    verticalLineTo(7f)
    moveTo(21f, 17f)
    verticalLineTo(19f)
    arcTo(2f, 2f, 0f, false, true, 19f, 21f)
    horizontalLineTo(17f)
    moveTo(7f, 21f)
    horizontalLineTo(5f)
    arcTo(2f, 2f, 0f, false, true, 3f, 19f)
    verticalLineTo(17f)
    moveTo(7f, 12f)
    horizontalLineTo(17f)
}


val LucideScanSearch = lucide("ScanSearch") {
    moveTo(3f, 7f)
    verticalLineTo(5f)
    arcTo(2f, 2f, 0f, false, true, 5f, 3f)
    horizontalLineTo(7f)
    moveTo(17f, 3f)
    horizontalLineTo(19f)
    arcTo(2f, 2f, 0f, false, true, 21f, 5f)
    verticalLineTo(7f)
    moveTo(21f, 17f)
    verticalLineTo(19f)
    arcTo(2f, 2f, 0f, false, true, 19f, 21f)
    horizontalLineTo(17f)
    moveTo(7f, 21f)
    horizontalLineTo(5f)
    arcTo(2f, 2f, 0f, false, true, 3f, 19f)
    verticalLineTo(17f)
    moveTo(9f, 12f)
    arcTo(3f, 3f, 0f, true, false, 15f, 12f)
    arcTo(3f, 3f, 0f, true, false, 9f, 12f)
    moveTo(16f, 16f)
    lineTo(14.1f, 14.1f)
}


val LucideSearch = lucide("Search") {
    moveTo(21f, 21f)
    lineTo(16.66f, 16.66f)
    moveTo(3f, 11f)
    arcTo(8f, 8f, 0f, true, false, 19f, 11f)
    arcTo(8f, 8f, 0f, true, false, 3f, 11f)
}


val LucideSettings = lucide("Settings") {
    moveTo(9.671f, 4.136f)
    arcTo(2.34f, 2.34f, 0f, false, true, 14.33f, 4.136f)
    arcTo(2.34f, 2.34f, 0f, false, false, 17.649f, 6.051f)
    arcTo(2.34f, 2.34f, 0f, false, true, 19.979f, 10.084f)
    arcTo(2.34f, 2.34f, 0f, false, false, 19.979f, 13.915f)
    arcTo(2.34f, 2.34f, 0f, false, true, 17.649f, 17.948f)
    arcTo(2.34f, 2.34f, 0f, false, false, 14.33f, 19.863f)
    arcTo(2.34f, 2.34f, 0f, false, true, 9.671f, 19.863f)
    arcTo(2.34f, 2.34f, 0f, false, false, 6.351f, 17.948f)
    arcTo(2.34f, 2.34f, 0f, false, true, 4.021f, 13.915f)
    arcTo(2.34f, 2.34f, 0f, false, false, 4.021f, 10.084f)
    arcTo(2.34f, 2.34f, 0f, false, true, 6.35f, 6.051f)
    arcTo(2.34f, 2.34f, 0f, false, false, 9.669f, 4.136f)
    moveTo(9f, 12f)
    arcTo(3f, 3f, 0f, true, false, 15f, 12f)
    arcTo(3f, 3f, 0f, true, false, 9f, 12f)
}


val LucideShare2 = lucide("Share2") {
    moveTo(15f, 5f)
    arcTo(3f, 3f, 0f, true, false, 21f, 5f)
    arcTo(3f, 3f, 0f, true, false, 15f, 5f)
    moveTo(3f, 12f)
    arcTo(3f, 3f, 0f, true, false, 9f, 12f)
    arcTo(3f, 3f, 0f, true, false, 3f, 12f)
    moveTo(15f, 19f)
    arcTo(3f, 3f, 0f, true, false, 21f, 19f)
    arcTo(3f, 3f, 0f, true, false, 15f, 19f)
    moveTo(8.59f, 13.51f)
    lineTo(15.42f, 17.49f)
    moveTo(15.41f, 6.51f)
    lineTo(8.59f, 10.49f)
}


val LucideShieldCheck = lucide("ShieldCheck") {
    moveTo(20f, 13f)
    curveTo(20f, 18f, 16.5f, 20.5f, 12.34f, 21.95f)
    arcTo(1f, 1f, 0f, false, true, 11.67f, 21.94f)
    curveTo(7.5f, 20.5f, 4f, 18f, 4f, 13f)
    verticalLineTo(6f)
    arcTo(1f, 1f, 0f, false, true, 5f, 5f)
    curveTo(7f, 5f, 9.5f, 3.8f, 11.24f, 2.28f)
    arcTo(1.17f, 1.17f, 0f, false, true, 12.76f, 2.28f)
    curveTo(14.51f, 3.81f, 17f, 5f, 19f, 5f)
    arcTo(1f, 1f, 0f, false, true, 20f, 6f)
    close()
    moveTo(9f, 12f)
    lineTo(11f, 14f)
    lineTo(15f, 10f)
}


val LucideSignal = lucide("Signal") {
    moveTo(2f, 20f)
    horizontalLineTo(2.01f)
    moveTo(7f, 20f)
    verticalLineTo(16f)
    moveTo(12f, 20f)
    verticalLineTo(12f)
    moveTo(17f, 20f)
    verticalLineTo(8f)
    moveTo(22f, 4f)
    verticalLineTo(20f)
}


val LucideSmartphone = lucide("Smartphone") {
    moveTo(7f, 2f)
    lineTo(17f, 2f)
    arcTo(2f, 2f, 0f, false, true, 19f, 4f)
    lineTo(19f, 20f)
    arcTo(2f, 2f, 0f, false, true, 17f, 22f)
    lineTo(7f, 22f)
    arcTo(2f, 2f, 0f, false, true, 5f, 20f)
    lineTo(5f, 4f)
    arcTo(2f, 2f, 0f, false, true, 7f, 2f)
    close()
    moveTo(12f, 18f)
    horizontalLineTo(12.01f)
}


val LucideSparkles = lucide("Sparkles") {
    moveTo(11.017f, 2.814f)
    arcTo(1f, 1f, 0f, false, true, 12.983f, 2.814f)
    lineTo(14.034f, 8.372f)
    arcTo(2f, 2f, 0f, false, false, 15.628f, 9.966f)
    lineTo(21.186f, 11.017f)
    arcTo(1f, 1f, 0f, false, true, 21.186f, 12.983f)
    lineTo(15.628f, 14.034f)
    arcTo(2f, 2f, 0f, false, false, 14.034f, 15.628f)
    lineTo(12.983f, 21.186f)
    arcTo(1f, 1f, 0f, false, true, 11.017f, 21.186f)
    lineTo(9.966f, 15.628f)
    arcTo(2f, 2f, 0f, false, false, 8.372f, 14.034f)
    lineTo(2.814f, 12.983f)
    arcTo(1f, 1f, 0f, false, true, 2.814f, 11.017f)
    lineTo(8.372f, 9.966f)
    arcTo(2f, 2f, 0f, false, false, 9.966f, 8.372f)
    close()
    moveTo(20f, 2f)
    verticalLineTo(6f)
    moveTo(22f, 4f)
    horizontalLineTo(18f)
    moveTo(2f, 20f)
    arcTo(2f, 2f, 0f, true, false, 6f, 20f)
    arcTo(2f, 2f, 0f, true, false, 2f, 20f)
}


val LucideTrash2 = lucide("Trash2") {
    moveTo(10f, 11f)
    verticalLineTo(17f)
    moveTo(14f, 11f)
    verticalLineTo(17f)
    moveTo(19f, 6f)
    verticalLineTo(20f)
    arcTo(2f, 2f, 0f, false, true, 17f, 22f)
    horizontalLineTo(7f)
    arcTo(2f, 2f, 0f, false, true, 5f, 20f)
    verticalLineTo(6f)
    moveTo(3f, 6f)
    horizontalLineTo(21f)
    moveTo(8f, 6f)
    verticalLineTo(4f)
    arcTo(2f, 2f, 0f, false, true, 10f, 2f)
    horizontalLineTo(14f)
    arcTo(2f, 2f, 0f, false, true, 16f, 4f)
    verticalLineTo(6f)
}


val LucideType = lucide("Type") {
    moveTo(12f, 4f)
    verticalLineTo(20f)
    moveTo(4f, 7f)
    verticalLineTo(5f)
    arcTo(1f, 1f, 0f, false, true, 5f, 4f)
    horizontalLineTo(19f)
    arcTo(1f, 1f, 0f, false, true, 20f, 5f)
    verticalLineTo(7f)
    moveTo(9f, 20f)
    horizontalLineTo(15f)
}


val LucideUser = lucide("User") {
    moveTo(19f, 21f)
    verticalLineTo(19f)
    arcTo(4f, 4f, 0f, false, false, 15f, 15f)
    horizontalLineTo(9f)
    arcTo(4f, 4f, 0f, false, false, 5f, 19f)
    verticalLineTo(21f)
    moveTo(8f, 7f)
    arcTo(4f, 4f, 0f, true, false, 16f, 7f)
    arcTo(4f, 4f, 0f, true, false, 8f, 7f)
}


val LucideVideo = lucide("Video") {
    moveTo(16f, 13f)
    lineTo(21.223f, 16.482f)
    arcTo(0.5f, 0.5f, 0f, false, false, 22f, 16.066f)
    verticalLineTo(7.87f)
    arcTo(0.5f, 0.5f, 0f, false, false, 21.248f, 7.438f)
    lineTo(16f, 10.5f)
    moveTo(4f, 6f)
    lineTo(14f, 6f)
    arcTo(2f, 2f, 0f, false, true, 16f, 8f)
    lineTo(16f, 16f)
    arcTo(2f, 2f, 0f, false, true, 14f, 18f)
    lineTo(4f, 18f)
    arcTo(2f, 2f, 0f, false, true, 2f, 16f)
    lineTo(2f, 8f)
    arcTo(2f, 2f, 0f, false, true, 4f, 6f)
    close()
}


val LucideVolume2 = lucide("Volume2") {
    moveTo(11f, 4.702f)
    arcTo(0.705f, 0.705f, 0f, false, false, 9.797f, 4.204f)
    lineTo(6.413f, 7.587f)
    arcTo(1.4f, 1.4f, 0f, false, true, 5.416f, 8f)
    horizontalLineTo(3f)
    arcTo(1f, 1f, 0f, false, false, 2f, 9f)
    verticalLineTo(15f)
    arcTo(1f, 1f, 0f, false, false, 3f, 16f)
    horizontalLineTo(5.416f)
    arcTo(1.4f, 1.4f, 0f, false, true, 6.413f, 16.413f)
    lineTo(9.796f, 19.797f)
    arcTo(0.705f, 0.705f, 0f, false, false, 11f, 19.298f)
    close()
    moveTo(16f, 9f)
    arcTo(5f, 5f, 0f, false, true, 16f, 15f)
    moveTo(19.364f, 18.364f)
    arcTo(9f, 9f, 0f, false, false, 19.364f, 5.636f)
}


val LucideWifi = lucide("Wifi") {
    moveTo(12f, 20f)
    horizontalLineTo(12.01f)
    moveTo(2f, 8.82f)
    arcTo(15f, 15f, 0f, false, true, 22f, 8.82f)
    moveTo(5f, 12.859f)
    arcTo(10f, 10f, 0f, false, true, 19f, 12.859f)
    moveTo(8.5f, 16.429f)
    arcTo(5f, 5f, 0f, false, true, 15.5f, 16.429f)
}


val LucideWifiOff = lucide("WifiOff") {
    moveTo(12f, 20f)
    horizontalLineTo(12.01f)
    moveTo(8.5f, 16.429f)
    arcTo(5f, 5f, 0f, false, true, 15.5f, 16.429f)
    moveTo(5f, 12.859f)
    arcTo(10f, 10f, 0f, false, true, 10.17f, 10.169f)
    moveTo(19f, 12.859f)
    arcTo(10f, 10f, 0f, false, false, 16.993f, 11.336f)
    moveTo(2f, 8.82f)
    arcTo(15f, 15f, 0f, false, true, 6.177f, 6.177f)
    moveTo(22f, 8.82f)
    arcTo(15f, 15f, 0f, false, false, 10.712f, 5.056f)
    moveTo(2f, 2f)
    lineTo(22f, 22f)
}


val LucideZap = lucide("Zap") {
    moveTo(15.914f, 4f)
    lineTo(6.914f, 13f)
    horizontalLineTo(10.916f)
    lineTo(8.086f, 20f)
    lineTo(17.086f, 11f)
    horizontalLineTo(13.089f)
    close()
}
